name: Publish package

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.4.2

      - name: Publish
        run: ./gradlew publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
